setwd('/home/kristine/Documents/17-18/4741project')
library(boot)
library(glmnet)
library(bestglm)
library(ROCR)

project <- read.csv('final_var/male_only.csv',header=TRUE,sep=';')


attach(project)

num_people = nrow(project)
project$race = as.factor(project$SAMPLE_RACE)
project$region = as.factor(project$REGION)
project$marriage = as.factor(project$MARSTAT_COL)
project$unemp = as.factor(project$UNEMP)
project$health = as.factor(project$HEALTHLIMIT)
project$hgr = as.factor(project$HIGHESTGRADE)
project$industry = as.factor(project$INDUSTRY)
project$urb = as.factor(project$URBAN_RURAL)
print(colnames(project))

attach(project)

race_region = table(race,region)
race_marriage = table(race,marriage)
race_health = table(race,health)
race_hgr = table(race,hgr)
race_industry = table(race,industry)
race_urb = table(race,urb)
region_marriage = table(region,marriage)
region_health = table(region, health)
region_hgr = table(region,hgr)
region_industry = table(region,industry)
region_urb = table(region,urb)
health_marriage = table(health,marriage)
marriage_industry = table(marriage,industry)
marriage_hgr = table(marriage,hgr)
marriage_urb = table(marriage,urb)
health_hgr = table(health,hgr)
health_industry = table(health,industry)
health_urb = table(health,urb)
hgr_industry = table(hgr,industry)
hgr_urb = table(hgr,urb)
industry_urb = table(industry,urb)


chisq.test(race_region)
chisq.test(race_marriage)
chisq.test(race_health)
chisq.test(race_hgr)
chisq.test(race_industry)
chisq.test(race_urb)
chisq.test(region_marriage)
chisq.test(region_health)
chisq.test(region_hgr)
chisq.test(region_industry)
chisq.test(region_urb)
chisq.test(health_marriage)
chisq.test(marriage_industry)
chisq.test(marriage_hgr)
chisq.test(marriage_urb)
chisq.test(health_hgr)
chisq.test(health_industry)
chisq.test(health_urb)
chisq.test(hgr_industry)
chisq.test(hgr_urb)
chisq.test(industry_urb)


cor.test(INCOME,YR_OUT,method="pearson")
cor.test(INCOME,AGE_ENT,method="pearson")
cor.test(INCOME,AFQT,method="pearson")
cor.test(INCOME,ASVAB,method="pearson")
cor.test(AFQT,ASVAB,method="pearson")
cor.test(AFQT,AGE_ENT,method="pearson")
cor.test(AFQT,YR_OUT,method="pearson")
cor.test(YR_OUT,AGE_ENT,method="pearson")
cor.test(YR_OUT,ASVAB,method="pearson")
cor.test(YR_OUT,AGE_ENT,method="pearson")


#print(hgrthink_hgp)
#https://www.r-bloggers.com/correlation-and-linear-regression/


